// ACE Electronics — Canonical product record shape.
//
// ONE source of truth. Storefront (today) and the admin panel (later) both read
// and write exactly these records. Nothing may define its own product shape.

import type {
  BadgeTone,
  CurrencyCode,
  ProductAvailability,
  ProductCategory,
  ProductCondition,
  ProductSubcategory,
} from './taxonomy'

/**
 * A product image. Images are a LIST of records — never image1/image2/image3.
 * Adding, reordering or re-flagging an image is pure data, never a schema change.
 */
export interface ProductImage {
  /** Permanent unique image ID (stable across renames of url/alt). */
  id: string
  /** Public URL or repo-relative path, e.g. '/products/laptops/x.jpg'. */
  url: string
  /** Accessible alt text. */
  alt: string
  /** Ascending display order within the gallery. */
  sortOrder: number
  /** Exactly one image per product should be primary (see normalizeProduct). */
  isPrimary: boolean
  /**
   * True when the image is representative studio imagery produced to depict the
   * model, rather than a photo of the specific physical unit.
   */
  aiGenerated?: boolean
}

/**
 * A single specification row. Data-driven key/value — NEVER a column per
 * possible laptop/phone/accessory attribute.
 */
export interface ProductSpecification {
  /** Permanent unique specification ID. */
  id: string
  /** e.g. 'Processor', 'RAM', 'Storage'. */
  label: string
  /** e.g. 'Intel Core i5, 10th Gen'. Always plain text. */
  value: string
  /** Ascending display order. */
  sortOrder: number
}

/** A short marketing/trust label rendered on cards and detail pages. */
export interface ProductBadge {
  id: string
  label: string
  tone: BadgeTone
}

export interface Product {
  /**
   * Permanent unique internal ID. Machine-generated, never derived from the
   * product name, an image filename or the slug, and never re-used or edited.
   */
  id: string
  /** Customer-facing URL slug. Unique, editable independently of `id`. */
  slug: string

  name: string
  brand: string
  category: ProductCategory
  subcategory?: ProductSubcategory
  description: string

  /** Numeric only. NEVER formatted currency text. */
  price: number
  /** Optional numeric sale price; when set and lower, `price` is the "was". */
  salePrice?: number
  currency: CurrencyCode

  condition?: ProductCondition
  availability: ProductAvailability
  stockQuantity: number

  featured: boolean
  /** false = archived/deactivated. Products are archived, never deleted. */
  active: boolean
  /** ISO timestamp set when the product was archived; undefined while active. */
  archivedAt?: string

  images: ProductImage[]
  specifications: ProductSpecification[]
  badges: ProductBadge[]

  /** Seller warranty for THIS product, e.g. '1-month ACE seller warranty'. */
  warranty?: string
  /** Free-text internal/customer note, e.g. '125pcs in stock, Kumasi'. */
  notes?: string

  /** ISO 8601 timestamps. */
  createdAt: string
  updatedAt: string
}

/**
 * Payload accepted when the admin panel creates a product. `id`, timestamps and
 * image/spec IDs are generated by the repository, so the admin never has to
 * invent an internal identifier.
 */
export type ProductDraft = Omit<
  Product,
  'id' | 'createdAt' | 'updatedAt' | 'images' | 'specifications' | 'badges' | 'currency' | 'active'
> & {
  currency?: CurrencyCode
  active?: boolean
  images?: Array<Omit<ProductImage, 'id'> & { id?: string }>
  specifications?: Array<Omit<ProductSpecification, 'id'> & { id?: string }>
  badges?: Array<Omit<ProductBadge, 'id'> & { id?: string }>
}

/** Partial update payload. `id` and `createdAt` can never be changed. */
export type ProductPatch = Partial<Omit<ProductDraft, never>>
